In [ ]:
import numpy as np


In [7]:
a=np.array([4,6,7,8,9,10])
b=np.array([2,4,8])
print("shape a:{}".format(a.shape))
print("shape b:{}".format(b.shape))


shape a:(6,)
shape b:(3,)


In [8]:
print("ndim {}".format(a.ndim))
print("ndim {}".format(b.ndim))

ndim 1
ndim 1


In [10]:
print("size {}".format(a.size))
print("size {}".format(b.size))


size 6
size 3


In [12]:
print(f"dtype {a.dtype}")
print(f"dtype {b.dtype}")


dtype int32
dtype int32


In [15]:
print(f"itemsize{a.itemsize}")

itemsize4


In [16]:
print(f"data{a.data}")

data<memory at 0x000002752B33F280>


In [13]:
x=np.array([[6,5,8],[6,9,2]])
y=np.array([[3,3,3],[2,2,2]])
np.add(x,y)

array([[ 9,  8, 11],
       [ 8, 11,  4]])

In [16]:
x1=np.array([[17,19,15,18],[5,9,16,20]])
y1=np.array([[10,12,13,11],[4,7,11,14]])
np.subtract(x1,y1)

array([[7, 7, 2, 7],
       [1, 2, 5, 6]])

In [17]:
x1=np.array([[17,19,15,18],[5,9,16,20]])
y1=np.array([[10,12,13,11],[4,7,11,14]])
np.mod(x1,y1)

array([[7, 7, 2, 7],
       [1, 2, 5, 6]])

In [21]:
x1=np.array([[17,19,15,18],[5,9,16,20]])
y1=np.array([[10,12,13,11],[4,7,11,14]])
np.multiply(x1,y1)

array([[170, 228, 195, 198],
       [ 20,  63, 176, 280]])

In [22]:
x1=np.array([[17,19,15,18],[5,9,16,20]])
y1=np.array([[10,12,13,11],[4,7,11,14]])
np.divide(x1,y1)

array([[1.7       , 1.58333333, 1.15384615, 1.63636364],
       [1.25      , 1.28571429, 1.45454545, 1.42857143]])

In [25]:
x1=np.array([[17,19,15,18],[5,9,16,20]])
y1=np.array([[10,12,13,11],[4,7,11,14]])
np.power(x1,y1)

array([[ 1654238625, -1987646927,  -642346289, -1480538112],
       [        625,     4782969,           0, -1879048192]])

In [26]:
x1=np.array([[17,19,15,18],[5,9,16,20]])
y1=np.array([[10,12,13,11],[4,7,11,14]])
np.absolute(x1,y1)

array([[17, 19, 15, 18],
       [ 5,  9, 16, 20]])

In [12]:
import numpy as np
a1=np.array([[4,7,9,5],[2,5,8,4]])
a2=np.array([[1,1,1],[3,3,3]])
sliced_arr=a1[:3,:3]
print(sliced_arr)





[[4 7 9]
 [2 5 8]]


In [15]:
index_arr=a1[[1,1],[2,1]]
print(index_arr)

[8 5]


In [16]:
print(a1.sum())

44


In [20]:
arr=np.array([[45,86],[34,59]])
print(arr.sum())

224


In [22]:
print(np.sqrt(arr))

[[6.70820393 9.2736185 ]
 [5.83095189 7.68114575]]


In [24]:
print(arr.T)

[[45 34]
 [86 59]]


In [29]:

r1=np.array([[23,34],[34,23]])
r2=np.array([[45,55],[55,45]])
matrix_multi=np.dot(r1,r2)
print(matrix_multi)

[[2905 2795]
 [2795 2905]]


In [30]:
bool=np.array([[True,True],[False,True]])

In [34]:
print("all() with axis none",np.all(bool))

all() with axis none False


In [46]:
temp=np.arange(4)
print(temp)
re=temp.reshape(2,2)
print(re)

[0 1 2 3]
[[0 1]
 [2 3]]


In [47]:
x=np.array([[15,32],[26,34]])
y=np.array([[59,62],[87,98]])
z=np.array([[38,49],[45,56]])
v=np.vstack((x,y,z))
h=np.hstack((x,y,z))
print("vstack:",v)
print("hstack:",h)

vstack: [[15 32]
 [26 34]
 [59 62]
 [87 98]
 [38 49]
 [45 56]]
hstack: [[15 32 59 62 38 49]
 [26 34 87 98 45 56]]


In [52]:
h_split=np.hsplit(h,3)
print("hsplit:",h_split)

hsplit: [array([[15, 32],
       [26, 34]]), array([[59, 62],
       [87, 98]]), array([[38, 49],
       [45, 56]])]


In [55]:
v_split=np.vsplit(h,2)
print("vsplit:",v_split)

vsplit: [array([[15, 32, 59, 62, 38, 49]]), array([[26, 34, 87, 98, 45, 56]])]


In [56]:
print("random:{}\n".format(np.random.random(20)))

random:[0.68370572 0.98592278 0.65831193 0.98685511 0.37467806 0.00474906
 0.46337627 0.80187069 0.79370409 0.38129644 0.97527178 0.84783418
 0.21341882 0.60457529 0.16761078 0.93624923 0.69283642 0.86448481
 0.23929711 0.06283406]



In [58]:
print("rand:{}\n".format(np.random.rand(3,4)))

rand:[[0.80697067 0.09314378 0.78604295 0.10129473]
 [0.24867425 0.99859342 0.27022235 0.85340112]
 [0.33498556 0.12158593 0.44353637 0.86761664]]

